haskell/process

cbits/runProcess.c

On Linux, the following program generates 10 zombie processes, one for each time that `callProcess` tries to call a nonexistent process.
import Control.Concurrent
import Control.Exception
import Control.Monad
import System.IO
import System.Process
ignoreIOException :: IOException -> IO ()
ignoreIOException _ = return ()
main = do
_ <- forkIO $ replicateM_ 10 $ callProcess "does-not-exist" [] `catch` ignoreIOException
_ <- getLine
return ()
The reason seems to be that the child PID leaks because the parent does not call waitpid() if the child has failed. This simple change seems to fix it.

Wait on child PID after failed exec

---

System/Process.hsc
changelog.md

This function is more flexible then readProcess, for example it allows
you to change the working directory before running the command.
This loses a bit in terms of error reporting. I'm also not sure if extending the API is the right thing to do. Another way to achieve what I want would be to expose withCreateProcess_, withForkWait, ignoreSigPipe, processFailedException functions in System.Process.Internals.

Add readCreateProcess function

---

tests/all.T
tests/process006.stdout

The first commit is needed for `process master` to pass GHC validation, after the recent addition of `readCreateProcess`.
The second commit makes the `process` testsuite compatible with some changes I have planned for the GHC test framework.

Update 2 GHC tests

---

System/Process.hsc

Building GHC on Windows shows the following warning:
libraries/process/System/Process.hsc:94:1: warning:
The import of ‘Foreign.C.Types’ is redundant
except perhaps to import instances from ‘Foreign.C.Types’
To import instances alone, use: import Foreign.C.Types()

Windows: delete redundant import in System/Process.hsc

---

System/Process/Internals.hs
cbits/runProcess.c

The motivation is that lots of processes behave differently when (especially) stdin is
closed vs when it's a pipe.

Add StdStream(NoStream) to have standard handles closed.

---

System/Process.hsc

"@since 1.2.3.0" is included verbatim in the last paragraph of readCreateProcess's documentation.  I think this occurs because there isn't a blank comment separating it from the last paragraph.

Add blank comment before "@since 1.2.3.0"

---

cbits/runProcess.c

Make sure stdin, stdout and stderr pipes are closed when exec call
fails, e.g. when the executable doesn't exist.
It is an attempt to fix #64. The code around is pretty complicated, I'm not 100% sure I'm doing everything right, so please review carefully. Anyway, it fixes the immediate issue I had in my application.

Close pipes on failure

---

System/Process.hs
changelog.md

The function was commented out and not used anywhere.
It's currently rather cumbersome to run a process in the background, perform some action, and close the process once your action is completed. I believe withCreateProcess can handle that use-case and just wasn't exposed.

Expose withCreateProcess to users.

---

System/Process/Internals.hs

The code `#if WINDOWS` works but is not really correct. GHC HEAD now
has a `-Wcpp-undef` warning that we would like to turn on and hence
need this fixed.

Fix CPP usage

---

cbits/runProcess.c

a9a8e91 added some `close` calls which attempted to close pipes that we already closed previously. This resulted in the error code we read from the failed child being overwritten, resulting in the `process004` test failing.

Don't close already closed pipes 

---

changelog.md
process.cabal

I'd like to deploy Win32 2.5 with GHC 8.4 but the version bounds on Directory are currently preventing this. As such I'd like to bump the bounds in Directory as well.
The release log for 2.5 is here https://github.com/haskell/win32/releases/tag/v2.5.0.0

Relax Win32 version bounds.

---

System/Process.hs

Clarify Binary properties of the streams

---

System/Process/Common.hs
System/Process/Internals.hs
changelog.md

This re-exports `CGid` (which was previously unusable on Windows due to its unavailability) from `System.Process.Internals`. It also re-exports the synonyms `GroupID` and `UserID` so that the Haddocks will have a place to point to on Windows.
Fixes #90.

Re-export CGid and friends from System.Process.Internals

---

System/Process/Posix.hs

As it is shadowed by other local bindings in this module.
It turns out this is necessary afterall.

System.Process.Posix: Hide mb_delegate_ctlc

---

System/Process.hs

The function is public, but the Haddock documentation isn't being rendered. I think it's a simple matter of removing the `{-` and `-}`, but I haven't tested locally.
Example render of missing documentation:
(from http://hackage.haskell.org/package/process-1.6.0.0/docs/System-Process.html)

Export withCreateProcess documentation

---

System/Process.hs
changelog.md
test/main.hs

Hello!
I believe I found a bug in `waitForProcess`. When run in the `MaskedInterruptible` state, an async exception doesn't actually bring the thread down.
For example, the `typed-process` library exports [`withProcess`](https://hackage.haskell.org/package/typed-process-0.1.0.0/docs/System-Process-Typed.html#v:withProcess) which is similar to [`withCreateProcess`](https://hackage.haskell.org/package/process-1.6.1.0/docs/System-Process.html#v:withCreateProcess), but ends up calling `waitForProcess` in the cleanup action of a `bracket`.
Even though `waitForProcess` is an `interruptible` foreign call, I think what's happening is:
- Async exception enqueued for delivery to thread making `waitForProcess` call
- GHC sees it's in an `interruptible` foreign call, sends `SIGPIPE` ([GHC …

Allow async exceptions to pierce masked waitForProcess

---

System/Process.hs

Previously it was not entirely obvious which handle corresponds to
stdin, stdout and stderr.

Improve documentation of withCreateProcess

---

changelog.md
process.cabal

Hi,
I'd like to bump up the Win32 version for GHC 8.4.
Win32 2.6 contains API breaking changes but those APIs aren't used by process.

Bump Win32 constraint up for GHC 8.4

---

System/Process.hs
changelog.md
test/main.hs

This implements my request #108
Tested on Linux and Windows. For Linux i used "stack test". For windows i did a seperate manual test (compared the PID with the info from the Task-Manger). The test/main.hs does not look like it could be run on Windows (for example echo is a builtin of cmd.exe and not a program on its own).
On Windows the PID stays valid as long as the handle is open (see https://blogs.msdn.microsoft.com/oldnewthing/20110107-00/?p=11803).

Added getPid

---

tests/Makefile
tests/T3994.hs
tests/T3994app.hs
tests/all.T

Calling `sh` and `sleep` can be quite flacky on Windows due to the msys2 runtime. 
It can result in random failures such as:
```
+      6 [main] sh 22832 child_copy: cygheap read copy failed, 0x1802F6408..0x1802FF298, done 0, windows pid 22832, Win32 error 299
+  16044 [main] sh 22832 C:/msys64/usr/bin/sh: *** fatal error in forked process - ccalloc would have returned NULL
```
So about that by using a Haskell program that does the same action. This makes the test stable again under Windows.

Process: fix flaky test.

---

tests/T3994.hs

Previous PR broke the test under Linux and MacOS due to the new binary not being on the `PATH`.
This version seems to work on Linux and Windows. Excuse the noise :(

Process: fix linux test build.

---

System/Process.hs

Clarify `terminateProcess`, closes #116

Update terminateProcess docs

---

process.cabal

See https://ghc.haskell.org/trac/ghc/ticket/15042.

Bump upper bound on unix to < 2.9

---

System/Process/Common.hs
System/Process/Windows.hsc

At some point we'd like to hide `GHC.IO.IOMode` from base. 
Related base change: https://phabricator.haskell.org/D4692

Import IOMode from System.IO instead of GHC.IO.IOMode

---

System/Process.hs
changelog.md

`cleanupProcess` needs to be exported in order to be able to write a version of `withCreateProcess` that works with MonadIO.

expose cleanupProcess

---

tests/process001.hs
tests/process002.hs

This should work on all the systems I've ever laid my hands on (not many, admittedly) and of particular interest to me and several other GHC/core libraries contributors who run GHC's testsuite, with this patch those tests now pass on NixOS.
``` sh
$ TEST="process001 process002" ./validate --fast --testsuite-only
[...]
==== STAGE 2 TESTS ==== 
SUMMARY for test run started at Tue Jun 12 15:51:02 2018 CEST
0:00:01 spent to go through
2 total tests, which gave rise to
14 test cases, of which
12 were skipped
0 had missing libraries
2 expected passes
0 expected failures
0 caused framework failures
0 caused framework warnings
0 unexpected passes
0 unexpected failures
0 unexpected stat failures
```
There, `ls` is not under `/bin` but somewhere in the nix store and brought into the PATH through …

process00{1,2} tests: just assume `ls` is in the PATH on non-Windows systems

---

process.cabal

GHC's build system runs `ghc-cabal check` on the cabal files for all of its
core libraries. One of the checks that this performs is to verify that base
has bounds. IMHO it's a bit silly that this is necessary even when base
is otherwise constrained by the library stanza so I've left the bounds
quite loose.

Add bounds on base in test-suite stanza

---

cbits/runProcess.c
changelog.md
include/runProcess.h

This fixes a potential privilege escalation issue (or, more precisely, privileges not being dropped when this was the user's intent) where the groups of the spawning process's user would be incorrectly retained due to a missing call to `initgroups`.
This also fixes an incorrect case fallthrough in the error message lookup logic.
Fixes #149.

Call initgroups before setuid

---

System/Process/Posix.hs
changelog.md

withCString doesn't allow undecodable bytes to round-trip through the
program, so use withFilePath to pack the environment. (It was already
used for packing the arguments.)
Closes https://github.com/haskell/process/issues/152

use withFilePath for environment variables

---

cbits/runProcess.c
changelog.md

The PR makes sure we're only listening to completion events for the `key` that we're interested in. This isn't much of an issue now but the new I/O manager for Windows will exclusively use I/O completion ports. Which means this method may mistakenly handle events it shouldn't have.
Secondly it fixes a rare but annoying condition. When you receive a notification on the port that a process has terminated this does not mean that the resources of the process has been flushed.
Previously we were immediately unregister the process once we get the notification. However things like `hsc2hs` which rely on the child process having written a file then may get into a race condition. Control may return to the caller before the file has actually been written.
Windows deals with this by returning an …

Windows: Check if all processes really exited and released resources

---

cbits/runProcess.c

Sorry, just noticed that in #159 it would exit the event loop if the event isn't ours.
It should continue listening not abort. This is mostly dead code till GHC 8.12 when there will be multiple events and event queues.

Don't exit when even isn't ours

---

tests/all.T

Previously we marked tests that aren't expected to pass under concurrent
execution as broken/fragile in threaded2, as that was the only way which
implied concurrent execution. However, this is not longer true due to
the introduction of the nonmoving_thr way.

testsuite: Tests broken threaded2 are broken in all concurrent ways

---

System/Process.hs

"\home\bob" does not form valid Haskell as there is no "\h" character.
Therefore, this line was changed to the *nix directory location it was intended
to be.
This closes #165.

Changed "\home\bob" to "/home/bob" in docs for System.Process.createProcess

---

System/Process.hs
System/Process/Common.hs
System/Process/Windows.hsc
cbits/runProcess.c
changelog.md
include/runProcess.h

This fixes the incorrect termination behavior described in #167. The path to get here was a bit meandering.
The "Check exit code of processes using jobs in two stages" commit refactors `waitForProcess` to ensure that the `ProcessHandle`'s `MVar` remains reachable throughout the blocking in `waitForJobCompletion`. It also updates the `MVar` after job completion and closes the OS handles to allow the process's resources to be freed.
However, I then realized that the Win32 documentation [explicitly states](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-jobobject_associate_completion_port) that the delivery of job IOCP notifications is not guaranteed. This is strange and appears to contradict the guidance given by [this blog …

Fix job support

---

System/Process/Windows.hsc
cbits/runProcess.c

GHC is able to see that the the `ClosedHandle` alternative is unreachable due to the containing `case` analysis.

Avoid redundant pattern match warning on Windows

---

cbits/runProcess.c
changelog.md
process.cabal

Unfortunately this change was incorrect and arose from following a misleading compiler warning without carefully checking the logic. Many apologies for the confusion and the bad release that resulted. 
With this reversion Windows finally finishes a GHC validation so I'm reasonably certain that this is release-worthy.
This reverts commit 062a69e2a5b4d5e51c896ee5d0433588b8f4d05c.

Revert "Check return value of QueryInformationJobObject"

---

cbits/runProcess.c

As noted in GHC #17926, the QueryInformationJobObject system call
apparently relies on the buffer size in addition to the
NumberOfAssignedProcesses field to determine how many results it should
return. For this reason it's important that we pass the true size of the
buffer to the call.

Windows: Fix buffer size of QueryInformationJobObject request

---

System/Process/Windows.hsc

Fixes #181, the documentation seems to have been misread, the argument to `_pipe` is the number of bytes to reserve for pipe communications, not the number of pipes to create.  This ended up making pipes that can only send 2 bytes at a time.
The pipes are created in blocking mode, so any write of larger than 2 bytes block and no read returns more than 2 bytes..
Instead use 8k which is the size of the internal Buffers in `Base` which back `I/O` calls.

Give a usable buffer to _pipe on Windows

---

System/Process.hs

If my reading of https://github.com/haskell/process/pull/58 and the code is correct, this new documentation note is also correct. But if it's not correct, that should *definitely* be documented.

Add note to waitForProcess about thread-safety

---

process.cabal

Context: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4082#note_300462

Bump base upper bound to 4.16

---

System/Process/Common.hs

I think this Haddock should be moved to the externally supported data definition.  Is that right?

Move Haddock from ProcessHandle__ to ProcessHandle

---

System/Process.hs
System/Process/Internals.hs
System/Process/Windows.hsc
changelog.md
process.cabal
test/main.hs

Hi,
`terminateJob` is being called from within `terminateProcess` which already has a lock on the `MVar`. 
This add a new function `terminateJobUnsafe` which does not take an `MVar` and so is not thread-safe but can be called from `terminateProcess` safely.
Fixes #196

GH196: Fix terminateJob

---

process.cabal

This should be the last change necessary for GHC 9.0. No new release is necessary but a Hackage revision would likely be best.
Thanks again!

Bump Win32 upper bound to accomodate Win32-2.10

---

System/Process.hs
changelog.md

This PR adds a new exported function in System.Process: `getCurrentPid`.
This calls `getCurrentProcessId` from System.Win32.Process on Windows, and `getProcessID` from System.Posix.Process on POSIX systems.
This seems like an oversight considering `getPid` is implemented already. I sometimes require the current running program's process ID. Currently, I have to do the CPP conditional logic myself every time, which is a pain. Putting this in `process` seems natural. 
Furthermore, my understanding of `process` is that it is a unified interface to System.Win32.Process and System.Posix.Process. As both modules provide a function to "get the currently executing process id", I feel it makes sense to have a cross-platform wrapper function.
The `@since` field has been left as a TODO since I'm not …

Implement getCurrentPid

---

cbits/posix/posix_spawn.c
test/main.hs

* Fix const-correctness in non-`posix_spawnp` codepath
* Consolidate Windows check in testsuite driver.

Two small fixes

---

cbits/posix/find_executable.c
cbits/posix/fork_exec.c
cbits/posix/posix_spawn.c
configure.ac
tests/all.T

Sadly, the refactor in #208 had a few issues which my earlier testing hadn't uncovered:
* the `posix_spawn` path didn't correctly handle the case where the platform does not support `POSIX_SPAWN_SETPGROUP`
* some compilers warned of missing (but in principle unreachable) cases, breaking the `-Werror` build in some cases
* `fork_exec`'s `setup_std_handle_fork` failed to return a value in some cases
* the `configure` script failed to declare its dependency on `<spawn.h>`, causing it to fail to find `posix_spawn` in some cases
* GCC 6.3 threw spurious warnings in `find_executable.c`, breaking the `-Werror` build
* the output expected by the GHC testsuite had a spurious platform dependence due to the new `posix_spawn` implementation
I have fixed all of these and tested on Linux, Darwin, and …

Various fixes for `posix_spawn` refactoring

---

cbits/posix/posix_spawn.c

*Editorial note:* @snoyberg, I'd like to again apologize for how many iterations this `posix_spawn` work has required; it really has been a compatibility nightmare. This particular issue remained under the radar in my Darwin testing on GHC as I had chalked it up to a GHC bug, having seen the same test fail for reasons unrelated to `process`. Sadly, this time the failure is actually due to a bug in Darwin's `posix_spawn_file_actions_adddup2` implementation. Thanks again, for your patience.
macOS Big Sur does not allow the user to `posix_spawn_file_actions_adddup2` an
fd to itself. Instead of behaving as a no-op as specified by POSIX
2017.1 (and as done by every other operating system), it instead fails with
`EBADFD` in `posix_spawn`. This caused a single tricky-to-identify
failure in GHC's …

posix_spawn: Don't attempt to dup2 identical fds

---

process.cabal

Fix #220: Bump lower bound of Win32 to 2.4
Since v1.6.12.0, process does not build any more with Win32-2.2/3.
I made the necessary revisions on hackage, but the next releases should include this PR.

Fix #220: Bump lower bound of Win32 to 2.4

---

tests/all.T

The reqlib modifier is going to be removed from the ghc testsuite.

Remove reqlib modifier from ghc test

---

cbits/posix/posix_spawn.c

In contrast to glibc, Darwin's posix_spawnp implementation doesn't set
errno on failure.
Fixes #227.

posix: Ensure that errno is set after posix_spawnp fails

---

System/Process.hs
test/main.hs

I believe this might address #226, which I've run across myself when interrupting processes spawned with `delegate_ctlc` within `withCreateProcess`. It turns out this isn't a race condition (though I'm not saying there are none), it's just that the first `withCreateProcess` call fails to close the handle when it throws `UserInterrupt`.
There's a test case that covers the original behaviour I saw (an uncaught exception when the subprocess is interrupted), and then a couple of test cases narrowing down to the actual bug.
I haven't tested this on Windows, and I'm not sure to what extent the tests make sense there -- we might need to adapt or skip them.

Fix waitForProcess not closing process handles with delegate_ctlc

---

cbits/posix/posix_spawn.c
changelog.md
configure.ac
process.cabal

It turns out that POSIX allows implementations to report
errors "lazily" by exiting the spawned process with code 127.
In particular, OpenBSD's implementation returns successfully if the
requested executable doesn't exist. This severely hampers our ability to
report errors accurately.
In this patch we add a `configure` test for sensible error-reporting
from `posix_spawnp` and disable it if the test fails.
Fixes #224.

configure: Ensure that posix_spawnp reports ENOENT correctly

---

tests/all.T
tests/process011.hs
tests/process011_c.c

The refactor of `process011` performed in 8cd7e04, where
the test is taught to use `python3` instead of `sh`, has broken the test
on Debian 10. Specifically, for reasons that I don't yet understand,
`python3` exits with code 1 not code 2 when killing itself with
signal 2. Strangely, my tests on other distributions (e.g. NixOS)
suggest that Python's behavior in this case is rather inconsistent.
To avoid this, we now rather use a dedicated C program instead of
Python.
Fixes #241.

testsuite/process011: Don't rely on Python

---

configure.ac

Hello,
quite recent addition for testing posix_spawn by running actual code broke cross-compiling capability. Simple hack fixes that
by assuming posix_spawn is working fine in this case.
E.g. see #232

fix cross-compiling configure issue

---

cbits/win32/runProcess.c
changelog.md

There's a small bug in the modes that we create handles with when we make inheritable handles.
We create both the input and output handles with `FILE_FLAG_OVERLAPPED`.
This is OK as long as the program being called is also not using IOCP. For the majority of the program
usually called this is the case and so we never noticed the bug in testing.
However when calling an application which is also using overlapped IO *or* uses the kernel low level
async APIs then the spawned application will misbehave because the operation would unexpectedly
become asynchronous.  This is the case with any program using Microsoft VC++'s stdlibs to read pipes.
The fix is to only mark handles with `FILE_FLAG_OVERLAPPED` if they are *not* being inherited.  That is,
only make them asynchronous if we, the caller …

winio: Fix Handle mode on inherited handles.

---

System/Process/Common.hs
changelog.md

This sets the default locale to be the current locale to match what the previous I/O manager was doing.
For WINIO the locale doesn't matter as all data is binary and we re-encode internally, however the locale seems to unexpectedly influence the line break detection in GHC.
As such we set the locale so it uses `\r\n` instead of `\n`.

winio: match mio in setting default encoding for pipes instead

---

cbits/posix/fork_exec.c

Darwin violates POSIX by making
`dup2(x,x)`, which should be a no-op, error. Consequently, we must take
care not to `dup2` in such cases.
We had already made this change in the `posix_spawnp` codepath but I had
assumed that this *only* affected `posix_spawnp`, not the `dup2` system
call itself.
See also: #214

cbits/fork-exec: Don't dup2 identical fds

---

cbits/posix/posix_spawn.c
tests/all.T
tests/processT251.hs
tests/processT251.stdout

Previously to spawn a process with a closed standard handle, we
would use `posix_spawn_file_action_addclose`. However, it turns out that
POSIX specifies that `spawnp()` may fail if `addclose()` is used on an
fd that is already closed. While glibc and musl appear to ignore this
aspect of the specification, Darwin indeed follows it leading to #251.
This behavior is rather unfortunate as
`posix_spawn_file_action_addclose` is a convenient way to close a handle
in a subprocess in a race-free manner (e.g. unlike `O_CLOEXEC`, which is
global). To avoid #251 we must first use
`posix_spawn_file_action_addopen` on the fd (e.g. opening `/dev/null`)
to be closed to ensure that it is valid, which has the side-effect of
closing the inherited fd. We can then safely use
`posix_spawn_file_action_addclose` …

Fix process#251

---

process.cabal

Fixes: #258
See: https://github.com/haskell/process/issues/258

Support `unix ^>=2.8`

---

tests/processT251.hs

It turns out that the test for `processT251` is subtly broken. In particular, the test will fail if any file is opened in the subprocess before the child is run since the closed fd 0 may be reused for the new file. This tends to happen in the threaded RTS due to the event manager's control pipe (see GHC #22395). Unfortunately, it's not really clear how else this can be reliably tested.
Given that this only touches the GHC bit of the testsuite which isn't usable via `cabal-install` or stack, I don't think an immediate release is strictly necessary here.

testsuite: Don't attempt to read from inherited fd in processT251

---

tests/all.T

Upstreaming marking the process tests as broken for the JavaScript backend that was just merged into GHC HEAD.
These tests are tracked on the GHC issue list [here](https://gitlab.haskell.org/ghc/ghc/-/issues/22349).
Please ping if anything needs to change with this PR. The CI for the JS backend is blocked on this, so its high priority for the JS team. 
Thanks!

GHC tests: mark process tests as broken for JS

---

process.cabal

Bump bounds to accomodate base-4.18

---

System/Process.hs
System/Process/Posix.hs
include/runProcess.h

This PR corrects an unfortunate mistake in #270. The `__wasm__` macro is a builtin system macro defined by `clang` when targetting `wasm32`, however, the autoconf scripts in GHC will automatically add `-undef` to the CPP flags that GHC uses to invoke `clang`, therefore this flag is unset and will result in a link-time error for `wasm32-wasi-ghc`.
After this fix lands, the existing test for cross GHC will also be updated to ensure these `process` functions are included as a part of the test to avoid any regression here.

Fix a non-existent macro unset by GHC

---

.github/workflows/tests.yml
cbits/win32/runProcess.c
changelog.md

The Windows kernel will release a process only when the last handle to it is closed.
This means that the call to `WaitForSingleObject` does not return until every other process closes any handles they may have opened to the program, including pipes passed to it.
However if on the Haskell side we haven't released the handle yet then we deadlock and wait indefinitely.  There is a race condition in that if when we get to `WaitForSingleObject` the kernel has already cleaned up the process then we'll return immediately, which is what is happening with the first test in the test program.
The old workflow for this wait function used to be that we iterate until the process list is empty.  On each we wait indefinitely.
The new workflow is different in that instead of waiting indefinitely we wait …

Windows: don't wait indefinitely on processes

---

cbits/posix/fork_exec.c

On Solaris, getpwuid_r(3) is only available when _POSIX_PTHREAD_SEMANTICS is defined.

Fix build on Solaris

---

System/Process/Common.hs
System/Process/Internals.hs
System/Process/Windows.hsc
changelog.md

This implements `delegate_ctlc` on Windows so the calling process can properly ignore SIGINT.
Without this cabal repl doesn't behave correctly.
validated working with manual tests and cabal.
to address https://github.com/haskell/cabal/issues/8820

Windows: Implement delegate_ctlc on Windows

---

cbits/posix/fork_exec.c
changelog.md
configure.ac

`vfork` is something of a relic, originally introduced as a (rather unsafe) optimisation of `fork` in 3.0BSD, allowing the user to eliminate the cost of cloning the parent process's address space (as early BSDs would do) when `fork`ing with the intent of immediately `exec`ing.
However, its design has long been considered a mistake (being nigh impossible to use safely in a multithreaded environment), its benefits have largely vanished (since modern operating systems rely on virtual memory to remap the parent's address space as copy-on-write instead of copying), and nearly all platforms now consider it to be an alias of `fork`.
Remove `process`'s support for `vfork`.
Fixes #261.

Drop vfork support

---

cbits/posix/fork_exec.c

@bgamari, this makes `processT251` pass on OpenBSD

cbits: Ensure that fork pipe doesn't shadow std fds 

---

cbits/posix/fork_exec.c

Fix #283, ensuring that failure of `find_executable` doesn't permanently stop the GHC ticker.
Address #284 by implementing `unshadow_pipe_fd` using `fcntl(F_DUPFD)`, considerably simplifying its implementation.

Address #284 and #283

---

cbits/posix/posix_spawn.c
configure.ac

I'm looking at improving performance when `close_fds=True` after encountering #189.
I noticed this could be improved on MacOS where this flag is available. Making the `do_spawn_posix` function handle more situations will result in fewer fallbacks to the (possibly less performant) `do_spawn_fork`.
I haven't tested this yet, hoping to see how it works on CI.

Use POSIX_SPAWN_CLOEXEC_DEFAULT in posix_spawn.c when available

---

cbits/posix/fork_exec.c
configure.ac

Previously we used `fork` followed by `fcntl` to create a pipe with `O_CLOEXEC`. However, this is potentially racy as another thread may `fork` in between in these two calls, resulting in the pipe of the former thread being available to the child of the latter.
Fix this by using `O_CLOEXEC` when creating the communications pipe.
Closes #287.

cbits/fork_exec: Eliminate potential leakage of comm. pipes

---

cbits/posix/posix_spawn.c
configure.ac

This reverts commit f47c8699eff0e2bfa37e5a096d905d9b88a558d6. This was incorrectly merged. See #254.

Revert "Use POSIX_SPAWN_CLOEXEC_DEFAULT in posix_spawn.c when available"

---

cbits/posix/find_executable.c
test/main.hs

The new test segfaults without the corresponding change in `find_in_search_path`
Using `.` is slightly less efficient than not using a working directory at all, but it avoids adding a third code branch and the consequent additional duplication of `sprintf` code.
Closes #295

Prevent a segfault in createProcess on Mac

---

System/Process.hs
System/Process/Common.hs
System/Process/Internals.hs
System/Process/JavaScript.hs
jsbits/process.js
process.cabal
tests/all.T
tests/process004.stdout-javascript-unknown-ghcjs
tests/process010.stdout-javascript-unknown-ghcjs

This PR adds support to the `process` package to target the `node.js` JavaScript platform using the GHC JavaScript backend.
This allows among other things the GHC JavaScript backend to use custom Cabal `Setup.hs` scripts.

Add support for the GHC JavaScript backend (node.js)

---

cbits/posix/posix_spawn.c
configure.ac

It appears that glibc still has not introduced support for `posix_spawn_file_actions_addchdir`, despite it being ratified by Austin Group. Add support for `posix_spawn_file_actions_addchdir_np` as a stop-gap solution since the removal of the `vfork` path has turned up some pathological cases in the `fork` path in user code.
Also fix a typo which rendered the previous `posix_spawn_file_actions_addchdir_np` path unusable.

posix_spawn: Add support for posix_spawn_file_actions_addchdir_np

---

cbits/posix/fork_exec.c

Previously the fork/exec backend would attempt to close stdin, et al. on process spawn failure. This result in spurious `close` failures due to `runInteractiveProcess` doing the same. Consequently, the cause of the failure would be confusingly mis-identified.
Fixes #306.

fork-exec: Don't double-close parent fds

---

System/Process.hs
System/Process/Common.hs
System/Process/Windows.hsc
changelog.md
process.cabal

The process library on Windows is vulnerable to a command
injection vulnerability, via cmd.exe's interpretation of
arguments. Processes that invoke batch files (.bat, .cmd) and
pass arguments whose values are affected by program inputs may be
affected.
Add some additional escaping to neutralise this scenario.
Also add some additional library documentation explaining how
arguments are processed on Windows.
Co-authored-By: Fraser Tweedale
HSEC-identifier: [HSEC-2024-0003](https://github.com/haskell/security-advisories/pull/188)

Address Windows command-line injection vulnerability

---

.github/workflows/tests.yml
.gitignore
Setup.hs
System/Process.hs
System/Process/Common.hs
System/Process/Internals.hs
cabal.project
process.cabal
stack.yaml
test/LICENSE
test/main.hs
test/process-tests.cabal
test/stack.yaml

The first commit moves the test-suite to a separate package. The rationale is that other work, such as #308, requires the test-suite to use a Custom setup in order to work around [Cabal bug #9854](https://github.com/haskell/cabal/issues/9854). If we don't split up the test-suite into a separate package, this would introduce a setup-depends dependency on the Cabal library, which would create a gnarly dependency cycle between `Cabal` and `process`.
The second commit rewrites the CI script. I did this because I couldn't figure out how to provision the `Cabal` library (needed by #308) across GHC versions with the current CI infrastructure.
There are a few other auxiliary changes, such as:
- Using Cabal version >= 2.4 in the .cabal files, and fixing the associated warnings,
- Using the CPP …

Move tests to separate process-tests package & update CI to use GitHub actions

---

.github/workflows/tests.yml
.gitignore
Setup.hs
System/Process.hs
System/Process/Common.hs
System/Process/CommunicationHandle.hs
System/Process/CommunicationHandle/Internal.hsc
System/Process/Internals.hs
System/Process/Windows.hsc
cabal.project
cbits/win32/runProcess.c
changelog.md
process.cabal
stack.yaml
test/LICENSE
test/Setup.hs
test/cli-child/main.hs
test/main.hs
test/process-tests.cabal
test/stack.yaml

**NB** This PR depends on #310. For review, please only look at the last commit (at the time of writing, this was a6af24e973249f8992c274feae382a5d341ad02b).
This PR adds the `System.Process.CommunicationHandle` module, which provides the cross-platform `CommunicationHandle` abstraction which allows `Handle`s to be passed to child processes for inter-process communication.
A high-level API is provided by the function `readCreateProcessWithExitCodeCommunicationHandle`, which can be consulted for further details about how the functionality is meant to be used.
To test this functionality, I added the new `cli-child` executable component to the library. To work around [Cabal bug #9854](https://github.com/haskell/cabal/issues/9854), it was necessary to change the build-type of the library to …

Add CommunicationHandle, an API for inter-process communication via Handles

---

.github/workflows/tests.yml

This accounts for the move of MacOS runners to `AArch64` for the `macos-14` image:
- Use both `macos-13` (x64) and `macos-14` (AArch64) images.
- Require GHC >= 9.2 on AArch64.
- Make sure to install autotools on MacOS images (`macos-14` seems to not have it).

Fix CI on MacOS AArch64 runners

---

.github/workflows/tests.yml
process.cabal
test/process-tests.cabal

I don't know what we should do about testing this, since `haskell-actions` doesn't have 9.10 yet. Should we wait for it to do so?
(Relatedly, I'm surprised that, since `process` is a boot library, that GHC could even release without this bump having already been performed. Maybe GHC just doesn't look at cabal version bounds at all.)

Bump to base < 4.21 (to support GHC 9.10)

---

process.cabal

This is useless at best, and a common source of confusion.
https://github.com/haskell/cabal/pull/10145
https://github.com/sol/hpack/issues/355

Remove `includes` from `.cabal`-file

---

System/Process/CommunicationHandle.hs
System/Process/CommunicationHandle/Internal.hsc
changelog.md
process.cabal
test/process-tests.cabal

We are now careful to not attach any finalizers to Handles when creating pipes for inter-process communication on Unix systems. Instead, the handles are closed manually.
The finalizers were causing problems in situations such as the following:
- the parent creates a new pipe, e.g. pipe2([7,8]),
- the parent spawns a child process, and lets FD 8 be inherited by the child,
- the parent closes FD 8 (as it should),
- the parent opens FD 8 for some other purpose, e.g. for writing to a file,
- the finalizer for the Handle wrapping FD 8 runs, closing FD 8, even though it is now in use for a completely different purpose.
This PR does not include a test, as the above bug is a bit difficult to trigger. My reproducer for this bug was a test in the `cabal-install` testsuite; I can confirm that the …

Don't attach finalizers to Handles in CommunicationHandle API

---

System/Process/Posix.hs

Posix: Do not treat arguments as `FilePath`

---

test/process-tests.cabal

Following up from the release of 1.6.22.0

Use correct version of process in process-tests

---

System/Process/Windows.hsc
changelog.md
process.cabal
test/process-tests.cabal

This change ensure the regime implemented for HSEC-2024-0003 is applied to batch file names ending with trailing chars that are ignored by Windows.

Prevent command-line injection for batch files with trailing char

---

cbits/posix/posix_spawn.c

Fixes #303. The previous fix in #304 unfortunately didn't resolve the issue, but I've tested with `strace` that this patch results in the right syscall.
It appears that CPP macro names are case sensitive, and the code was previously checking for `HAVE_posix_spawn_file_actions_addchdir` whereas Autoconf defines `HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR`. This meant that calls to `createProcess` which set `cwd` to a `Just` value would always fail to use `posix_spawn` and instead fall back on `fork`, which is problematic when the parent process has a large residency.
Testing the fix revealed another issue, which is that `_GNU_SOURCE` must be defined before any glibc headers are included, otherwise the `_np` variant provided by glibc will not be declared.

Correctly detect posix_spawn_file_actions_addchdir[_np]

---

System/Process/Common.hs

This was added in #292. CC @luite

Remove extraneous Haddocks comment

---

cbits/posix/common.h
cbits/posix/runProcess.c

Fixes #342. Prior to this change, configuring with `ac_cv_func_fork=no` would result in linker errors due to missing symbols. By moving the `HAVE_FORK` checks, configuring with  `ac_cv_func_fork=no`  now results in `do_spawn` failing at runtime if the `fork` path is needed (e.g. if `posix_spawn` was not supported).

Support being configured without fork
