haskell/process

.travis.yml, cbits/runProcess.c, changelog.md, process.cabal, test/main.hs
Pinging @hvr. Looks like I don't have write access on this repo either. Sorry to be a nuisance.
=> 3649 does not exist exc

System/Process/Internals.hs
Hi,
I would like to thank a lot of effort.
I added stopDelegateControlC function for MinGW32.
Please check:-)
=> Add stopDelegateControlC for MinGW32

System/Process/Internals.hs
Hopefully they won't break it again? :)
=> Fix broken link for "Parsing C Command-Line Arguments"

changelog.md, process.cabal
minor tweak, may not worth merging
/cc @snoyberg
=> 1.3 changelog: unreleased -> August 2015

System/Process.hsc
Sorry for not fixing this in my previous commit.  I didn't realize the same problem was repeated.  :(
=> Join more sentence fragments

System/Process/Common.hs
Here's a pull request for issue #54.  I also added Eq, though I don't have an immediate use for it.  Same logic applies as Show though.
=> Add Show and Eq instances to CreateProcess, CmdSpce, and StdStream.

System/Process/Common.hs
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>
=> Add a remark on how relative cmdspec is resolved w.r.t. to cwd.

process.cabal
=> process.cabal: Use Hackage URL for typed-process

process.cabal
See https://ghc.haskell.org/trac/ghc/ticket/15018.
=> Bump upper bound on base to < 4.13

System/Process/Common.hs
As discussed on #50 improve the documentation for `NoStream`
=> Improve documentation for NoStream

System/Process.hs
This warning will soon be enabled by -Wall (See Trac #15656).
=> Fix a -Wincomplete-uni-patterns warning

tests/all.T
See [GHC #16547](https://gitlab.haskell.org/ghc/ghc/issues/16547).
=> testsuite: Omit process005 in ghci way

System/Process.hs
Clarify what it means to be unsuitable for running interactive processes
=> Clarify documentation for readProcess

System/Process/Common.hs
Just a quick additional comment, to make people aware, that close_fds is potentially expensive. I was hit by this in ndmitchell/shake#722.
=> Add comment about slow close_fds

tests/all.T
=> testsuite: Mark process003 as fragile

appveyor.yml, process.cabal, stack-new-win32.yaml
=> Allow newer Win32

tests/process011.hs
Silences -Wcompat-unqualified-import warning.
=> testsuite: Qualify import of Data.List

process.cabal
=> Bump win32 bounds

process.cabal
=> Bump base upper bound

System/Process.hs, System/Process/Posix.hs, cbits/posix/fork_exec.c, cbits/posix/posix_spawn.c, cbits/posix/runProcess.c, include/runProcess.h
This one is a rework of #240 and shouldn't break CI in this repo or any other GHC platforms now.
=> Fix compilation for wasm32-wasi

tests/all.T
GHC ticket: https://gitlab.haskell.org/ghc/ghc/-/issues/23059
=> Update tests for the new test way `ghci-opt`

process.cabal
=> Bump base bound to <4.20

.gitignore, System/Process/Windows.hsc, process.cabal, test/process-tests.cabal
See details: https://gitlab.haskell.org/ghc/ghc/-/issues/24603#note_565835
=> Add Support for Windows Aarch64
